#!/usr/bin/env python
import sys
import rdflib

# Parse arguments
if len(sys.argv) != 3:
    sys.stderr.write("usage: Usage: rdfa2ttl https://example.org/foo/ /var/www/example.org/foo/index.html\n")
    sys.exit(1)
baseIRI = sys.argv[1]
file = sys.argv[2]

# Extract and convert RDFa
g = rdflib.Graph()
g.parse(file, format='rdfa', publicID=baseIRI)
print(g.serialize(format='nt'))
